server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jguardiolagarcia/microservice-java
          search-paths: config-data
  application:
    name: config-service